6 update doc strings
noraa-july-stoke/tangerine pull request #17
Opened 2023-05-11 05:28 UTC by Kkorbin

I am a bit behind the main branch. There are some merge conflicts. 😓 I figure it would be best for you to sort out what you do and don't want. 

Let me know if there is anything I need to change. Thanks! 😁

2023-05-11 18:01 UTC, noraa-july-stoke requested changes
I think it was the refactor on yuzu class that's causing the problem. Any way you can remove the changes from yuzu.py and tangerine.py and then push the work back up again?

2023-05-11 18:42 UTC, Kkorbin commented
Okay. I will remove my doc changes to Tangerine and Yuzu. That will resolve the issue. 😅

2023-05-12 00:31 UTC, Kkorbin commented
@noraa-july-stoke I reverted my changes to tangerine and yuzu if you want to see if it merges without issue now. Thanks! 😁

2023-05-12 03:14 UTC, noraa-july-stoke approved these changes

2023-05-12 03:15 UTC, merged